### ISSUE TITLE
Error Building on Ionic 2

### ISSUE THREAD

**Issue by wac2007** [localForage/localForage-observable#13]
When I was compiling my App (Ionic 2) the webpack gives me this error

<img width="1070" alt="captura de tela 2017-06-08 as 07 15 31" src="https://user-images.githubusercontent.com/1892294/26924024-635db5ee-4c1a-11e7-9ec3-2080ddb81a5d.png">
<img width="900" alt="captura de tela 2017-06-08 as 07 15 44" src="https://user-images.githubusercontent.com/1892294/26924023-635d99b0-4c1a-11e7-9106-832c5a5e3b69.png">

**Comment by thgreasi** [comment]
Ionic storage (which I think come pre-installed w/ ionic) uses localforage v1.4 + the respective `@types`.
The easy & dirty fix would be to just delete `node_modules/@types/localforage` (please try this initially and post back your findings).
You will probably have to use v1.1 of this library which is compatible with localforage v1.4 that ionic uses.

There is already [a PR in ionic-storage to upgrade their localforage dependency](https://github.com/ionic-team/ionic-storage/pull/78).

**Comment by wac2007** [comment]
Deleting ``node_modules/@types/localforage`` fix the problem. Thanks!

**Comment by thgreasi** [comment]
👍 Cheers
Can I ask you a favor?
Can you try restoring the `@types/localforage` folder (eg with a new `npm i`) and try setting the `exclude` property of your `tsconfig.json` to
```js
    "exclude": [
        /* ... , */
        "node_modules/@types/localforage"
    ]
```
and report back your findings?
