### ISSUE TITLE
clear() doesn't trigger event

### ISSUE THREAD

**Issue by seb-ster** [localForage/localForage-observable#15]
Using the code below, i don't seem to get an event for the `localforage.clear()` method.

```
import localforage from 'localforage'
import 'localforage-observable'

let store = localforage.createInstance({name:'clear-test'})
store.ready(function() {
  let observable = store.newObservable({
  })
  observable.subscribe({
    next: function(args) {
      console.log('observable', args);
    }
  })
})

store.setItem('1','test')
.then(()=>{store.clear()})
```
I do get an event on the `setItem()` method.
The 'clear-test' database is emtpy afterward, so the `clear()` method worked.

Tested on FF 58.0.2 and IE 11.248
localforage: 1.5.3 and 1.6.0
localforage-observable: 1.4.0

**Comment by thgreasi** [comment]
Hi there, thanks for reporting this.
Ok what driver does the above happen?

**Comment by seb-ster** [comment]
I havn't specified a driver, but the 'clear-test' database appears in the Indexed DB in the browser.

I forgot to mention the versions for localforage and localforage-observable i was using:

localforage: 1.5.3
localforage-observable: 1.4.0

I updated localforage to version 1.6.0 but the issue remains

**Comment by thgreasi** [comment]
It seems that it only works when change detection is off. I don't remember having a specific reasoning for that case or doing this on purpose. Will continue investigating and will probably also add proper tests.
Once again thanks for the report.

**Comment by thgreasi** [comment]
I've started converting this repo to Typescript. I will continue during the next weekend and hopefully will also fix this.

**Comment by seb-ster** [comment]
So, i came back to this issue as i ran into some problems with change detection being off.

A change event has an object as payload. The object has, `oldValue` and `newValue` properties.
In case of the `clear()` method `oldValue` and `newValue` properties both are null. Even if data was definitly cleared from storage.
Could it be that change detection is not working because `oldValue` does not correctly reflect the old values? `oldValue `and `newValue `are both null, giving the impression no change happened?

What should the value of `oldValue` be in case of a `clear()` event, as it affects multiple old values?
Well, the value of the `key` property is `undefined`.
As per [LocalForage Documentation](https://localforage.github.io/localForage/#data-api-getitem) `undefined` is not used in storage. So the property `oldValue` can never be `undefined`.

My suggestion:
Why not use the `undefined` value on `oldValue` in case of the `clear()` method?
Which would be consistent with the `key` property value.

**Comment by thgreasi** [comment]
When change detection is off, we actually don't populate the oldvalue at all, we instead just listen for the various localforage method calls and fill the newvalue with their payload.
Status update: I've finished converting this repo to typescript and configured karma with headless chrome as well. Didn't have time for the last 3 weekends but will resume soon.
