### ISSUE TITLE
I'm interested in what this adds to localForage's promise based api?

### ISSUE THREAD

**Issue by ichpuchtli** [localForage/localForage-observable#2]
Really well documented project btw. The API definition in typescript is a nice idea I wish other people would follow. 

I'm interested in the value of this project though. 

Is it just converting a localforage promise to a one shot observable?
If so a generic function to convert promise to one shot observables like RxJS `Rx.Observable.fromPromise()` should be used in a project.

**Comment by thgreasi** [comment]
It actually lets you observe the active localforage driver for method
invocations that affect the database. Moreover it provides a way to get
notified whenever the value associated with a specific key changes.
Take a look at the examples.
I guess I have to make this clear in README.

> ## 
> 
> _Thodoris Greasidis_
> Computer, Networking &
> Communications Engineer
