### ISSUE TITLE
How to merge multiple observables in to one?

### ISSUE THREAD

**Issue by Itrulia** [localForage/localForage-observable#3]
I've tried the following

CacheService.ts

```
public getObservable(key) {
        return this.localForage.newObservable({key: key}).map((item:any) => {
            return this.getItemContent(key, item);
        });
}
```

Doesn't fire the subscribe methods

```
return Observable.from(teamIds).flatMap((teamId:any) => {
    return this.CacheService.getObservable(this.getTeamCacheKey(teamId));
});
```

Doesn't fire the subscribe methods either

```
let observables = teamIds.map((teamId:any) => {
    return this.CacheService.getObservable(this.getTeamCacheKey(teamId));
});

//noinspection TypeScriptUnresolvedFunction
return Observable.concat(observables).flatMap((x:any) => {
    return x;
});
```

note: When I use .map instead of .flatMap it works, but it returns the single Observables which I do not want :)

**Comment by thgreasi** [comment]
I wasn't able to find [Observable.concat()  as part of zen-observable](https://github.com/zenparsing/zen-observable/blob/master/zen-observable.js)!?!?!?
Are you using Zen-Observavle or RxJS5 ???
If you are using RxJS, then [have you patched the Observavle factory as shown in README](https://github.com/thgreasi/localForage-observable#using-a-different-observable-library)?

**Comment by Itrulia** [comment]
rxjs5 and patched as shown in the README, but I found the cause, you don't get the item even if its already set.

Setting `CacheService.setItem("9894165", "...");` triggered the observable, but I don't get data from the start it seems. Is this the wanted behaviour? 

Because getting the data if it's set should be _the_  use case for a caching layer, shouldn't it? :D

**Comment by thgreasi** [comment]
I'm afraid I couldn't understand your last comment correctly. Please check out the provided examples.
In case that the actual value of the item didn't change, then the Observable will not fire.
For example, lets say that ItemA has the value "A". Then the following code will only fire the Observavle once:

``` js
localforage.setItem('ItemA', 'newValue').then(function() {
    return localforage.setItem('ItemA', 'newValue');
}).then(function() {
    return localforage.setItem('ItemA', 'newValue');
}).then(function() {
    return localforage.setItem('ItemA', 'newValue');
});
```

**Comment by Itrulia** [comment]
It's a shame that it doesn't return the data if it already exists, which also kinda defeats the purpose of the caching layer..

**Comment by thgreasi** [comment]
> It's a shame that it doesn't return the data if it already exists

That's not true.
The observable by default notifies its subscribers only when the value is
actually changed or when it is initially set. So, setting the same value
does not trigger anything.
(This way you can avoid unnecessary cache invalidations.) Think it like the
$watch method that actually provides.

On the other hand, you can actually initialize an observable having the
change detection disabled by setting [`changeDetection: false`](https://github.com/thgreasi/localForage-observable/blob/master/README.md#value-change-detection).
In this scenario the observable gets notified on every write operation on
the database, even when setting the same value on an existing key. Is this

## sufficient/better suited for your use case?

_Thodoris Greasidis_
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
In the previous example, running  `localforage.setItem('ItemA',
'newValue2');` after the last `localforage.setItem('ItemA', 'newValue');`
completes, would result your observable to get notified about the newValue2
value change on ItemA.

> ## 
> 
> _Thodoris Greasidis_
> Computer, Networking &
> Communications Engineer

**Comment by Itrulia** [comment]
> Is this sufficient/better suited for your use case?

Actually no, since I do not want to reset the cache expiration time, what I just did is using a callback which I pass in to the subscribe and promise at the same time.
