### ISSUE TITLE
localforage.setItem in a promise won't fire Observable with rxjs

### ISSUE THREAD

**Issue by Itrulia** [localForage/localForage-observable#4]
So I have this method which pulls user data from the server and then caches it via localforage. When I set the data in a promise the Observable isn't fired.

UserCacheProxy

```
public getUsers(userIds: string[], callback: NextObserver<any> | Function) {
    let cacheKeys = userIds.map((userId:any) => {
        return this.getUserCacheKey(userId);
    });

    let applyCallback = (item) => {
        this.$rootScope.$apply(() => {
            callback(item);
        });
    };

    //noinspection TypeScriptUnresolvedFunction
    let subscriber = Observable.from(cacheKeys)
        .flatMap((key) => {
            this.CacheService.getItem(key)
                .then((user: IApiUser) => {
                    return new ngLeague.User(user);
                })
                .then(applyCallback)
                .catch(x => x);

            return this.CacheService.getObservable(key);
        })
        .map((user:IApiUser) => {
            console.log(user);
            return new ngLeague.User(user);
        })
        .subscribe(applyCallback);

    this.CacheService.setItem("user:9373305", "Hi", this.CachingTimes.getUserCacheTimeout());

    this.fetchUncachedUsers(userIds).then((users) => {
        this.CacheService.setItem("user:9373305", "Hi2", this.CachingTimes.getUserCacheTimeout());

        _.forEach(users, (user: IApiUser) => {
            let cacheKey = this.getUserCacheKey(user.id);
            this.CacheService.setItem(cacheKey, user);
        });
    });

    return subscriber;
}
```

Which I call like that:

```
UserCacheProxy.getUsers(["9373305"], function(user:ngLeague.User) {
    // do nothing
});
```

Expected result:

```
User {apiData: "Hi"}
User {apiData: "Hi2"}
User {apiData: "{..}"} // actual user data from the server
```

Actual result:

```
User {apiData: "Hi"}
```

Note: 
- Also happens without the `$rootScope.$apply` from angular
- Doesn't matter if item already exists in the database or not

**Comment by thgreasi** [comment]
The [examples found in README](https://github.com/thgreasi/localForage-observable#examples) call `setItem()` inside a Promise without any issue.

I'm trying hard to help you but the above code doesn't describe neither the parameters that the `localforage.newObservable()` was called with nor the actual `setItem()` call. Does the `fetchUncachedUsers` even return?
It would be great if you can fork one of the examples to prove your use case.

**Comment by Itrulia** [comment]
Yes the promises returns, I did a temporary fix where I call the callback by hand for each user in the promise. I use rxjs though. I try to create a pen for you

**Comment by thgreasi** [comment]
Can you please provide the implementation of the `this.CacheService.getObservable(key);` method?

**Comment by Itrulia** [comment]
http://codepen.io/Itrulia/pen/jqjrGb

as soon as you use rxjs it doesnt work anymore.

Here the implementation of getObservable

```
protected getItemContent(key:any, item:any) {
        if (item !== null && item.hasOwnProperty("newValue")) {
            item = item.newValue;
        }

        if (item !== null && item.content !== null && !this.isExpired(item)) {
            return item.content;
        }

        if (this.isExpired(item)) {
            this.removeItem(key);
        }

        return null;
    }

public getObservable(key) {
        return this.localForage.newObservable({
            key: key,
            setItem: true,
            removeItem: false,
            clear: false,
            changeDetection: false
        }).map((item:any) => {
            return this.getItemContent(key, item);
        });
    }

```

since you don't see how expires and content are set:

```
public setItem(key, value, timeout = null) {
        timeout = timeout || moment.utc().add(10, "minutes");
        timeout = timeout.format("X");

        let item = {
            expires: timeout,
            content: value
        };

        return this.localForage.setItem(key, item).then(() => {
            return item.content;
        });
    }
```

**Comment by thgreasi** [comment]
[README states that you should use RxJS5](https://github.com/thgreasi/localForage-observable#requirements). I haven't ever tried it with RxJS 4, this might be the issue.

**Comment by Itrulia** [comment]
http://codepen.io/Itrulia/pen/jqjrGb

doesn't change (I use rxjs5, i just grabbed the wrong version from cdnjs for the pen). Unfortunately they do not have the bundled version on cdnjs/github so I just inlined it.

**Comment by thgreasi** [comment]
Is [this](http://codepen.io/thgreasi/pen/BKgzxB) ok?

**Comment by thgreasi** [comment]
It fires 3 times for the saved user object, with the new passwords each time.
It seems that RxJS 5 **does** change the results.

**Comment by thgreasi** [comment]
Should we close this?

**Comment by Itrulia** [comment]
Hm.. okay, seems strange, yeah we can. I need to investigate further it seems. Thanks!

**Comment by Itrulia** [comment]
Update: Seems like localforage.ready(function() {}); is really needed, hm..

**Comment by Itrulia** [comment]
So, I found the issue. Your library needs localforage.ready(function() {}); before setting an item, fortunately .ready returns a promise so we can just wrap it like that:

```
public setItem(key, value, timeout = null) {
        timeout = timeout || moment.utc().add(10, "minutes");
        timeout = timeout.format("X");

        let item = {
            expires: timeout,
            content: value
        };

        return this.localForage.ready(function() {}).then(() => {
            this.localForage.setItem(key, item).then(() => {
                return item.content;
            });
        });
    }
```

**Comment by Itrulia** [comment]
Maybe mention in the docs? :D

**Comment by thgreasi** [comment]
README does mention that: [Currently localForage Observables should only be created after localforage.ready(), so that localForage completes the initialization of the requested (or best matching) driver. Moreover, Observables will stop working in case you change the driver in use, after their creation.](https://github.com/thgreasi/localForage-observable#usage).

**Comment by Itrulia** [comment]
Im an idiot.. Thanks! (not my day, spent multiple hours bugfixing jasmine crashes already)
