### ISSUE TITLE
Add support for cross-tab notifications

### ISSUE THREAD

**Issue by thgreasi** [localForage/localForage-observable#5]
As noted in:
localForage/localForage#104
localForage/localForage#244
localForage/localForage#622

**Comment by dmurph** [comment]
Indexedb observers are now working behind a flag in Canary

**Comment by thgreasi** [comment]
That's great. I'm thinking about an initial release using localstorage to propagate cross tab events. After IndexedDB events gets implemented without a flag from one more browser engine, we can plan upgrading the architecture.

**Comment by TheNeikos** [comment]
Thanks a lot for working on this!

**Comment by dmurph** [comment]
Awesome! If you have any time to take a look at the current API (see sample here:
https://googlechrome.github.io/samples/indexeddb-observers/) any feedback would be greatly appreciated.

**Comment by thgreasi** [comment]
Just opened PR #6. It would be great to receive some feedback and then release during the weekend.

**Comment by thgreasi** [comment]
Just meged #6 and released v1.1.0 which includes cross-tab observation.

**Comment by TheNeikos** [comment]
Thanks a lot. Going to implement this now

**Comment by deiu** [comment]
Hi! Is this feature supported in all browsers? It would be useful to have a note in the README about current browser support.

Also, are there any plans to merge this feature into the main repo?

Edit: I'm only interested in support for IndexedDB, not localStorage.

**Comment by thgreasi** [comment]
@deiu This is based on localStorage events, so it should work wherever localStorage is supported.
My main concern would be private browsing, which essentially beats the purpose, since the user by definition requests for an isolated tab, so this should be a non-issue.

**Comment by deiu** [comment]
Thanks for the quick reply! I see. I knew the eventListener for localStorage is available but for some reason I'm thinking by default of IndexedDB when using localForage. After reading the thread again, I see you mentioned waiting for native IndexedDB support in browsers.
