### ISSUE TITLE
Use LocalForage-observable in an es6/typescript environment

### ISSUE THREAD

**Issue by jloosli** [localForage/localForage-observable#7]
I'd like to use localforage-observable in a typescript project (Angular2). What is the correct way to import and use it using es6 modules? For example, I can use localforage in a module by importing it:

```
import * as localforage from 'localforage';
```

Localforage-observable just extends localforage, but I can't figure out how to include it and extend localforage. I've tried each of the following to no avail (including the above statement every time):

```
import * as lo from 'localforage-observable';
import 'localforage-observable';
require('localforage-observable');
const lo = require('localforage-observable');
```

None of those work. Can you point me in the right direction?

**Comment by thgreasi** [comment]
You should be able to use this extension by importing it right after localforage itself, using a similar import statement.

In ES6 you should do:
```js
import * as localforage from 'localforage';
import * as lo from 'localforage-observable'; // OR just import  'localforage-observable';

var observable = localforage.newObservable();
localforage.setItem('test', 'testvalue');
```

This lib is currently missing some typings. Also, the fact that it extends the localforage prototype might make it even worse for typescript users. I will try to find out a solution during the weekend.

**Comment by Itrulia** [comment]
`import "localforage-observable` does not work because it can't find the window module. `import * as lo from "localforage-observable` does work though. atleast it doesn't throw an error, but it can't find newObservable on localForage.


edit: `import window from 'window';` fucks it up in `localforage-observable.es6.js`. When trying to `console.log(lo)` with the other method it also breaks with the same error.

**Comment by thgreasi** [comment]
Typescript will not be able to find `newObservable` since we are currently missing some typings. To be honest I never actually tested this lib with typescript.
Have you tried localforage-observable.js ?
Also, can you give some feedback on v1.0.0, which doesn't contain the aforementioned `import window from 'window'` expression?

Thanks for the feedback so far!

**Comment by Itrulia** [comment]
with `import * lo from "localforage-observable` the newObservable object isn't found on localForage in the browser, not in the typings :)

`localforage-observable/dist/localforage-observable.js` has the same window error. Trying the v1,0,0 now

**Comment by Itrulia** [comment]
v1.0.0 is working

**Comment by thgreasi** [comment]
I guess that you only get `newObservable` in the browser and not in Typescript.
Ok, great. I know what I have to change. I will try to release v1.1.1 tonight and v1.2.0 with proper typings during the weekend!

**Comment by Itrulia** [comment]
Nah when you do: `import * lo from "localforage-observable"` it seems like that the code to append it is never executed or is working on another reference? `console.log` didn't bring it up and 

```
this.db$ = fromPromise(localForage.ready()).map(x => localForage);
this.db$.take(1).subscribe(db => {
    db.newObservable.factory = (fn) => Observable.create(fn);
});
```

threw an error trying to access factory of undefined in the browser.


Thanks!

**Comment by thgreasi** [comment]
It seems to [work on the browser even on other instances](http://codepen.io/thgreasi/pen/oZoPOE), I will check it out on an Ionic project tonight.

**Comment by Itrulia** [comment]
Well it isn't using imports and thats the problem :D

**Comment by thgreasi** [comment]
Just released v1.1.1 that should fix the `window` error. Starting writing the Typings now. Any confirmation would be appreciated.

**Comment by Itrulia** [comment]
Will check tomorrow, thanks!

**Comment by jloosli** [comment]
I tested using v1.1.1 and got the following to almost work:

```
import * as localforage from 'localforage';
import 'localforage-observable';

...

(localforage as any).newObservable({key: 'pending'}).subscribe((args) => console.log(args));
```

When I get to the newObservable part, I get the following error: `ReferenceError: Observable is not defined`. 
This is in reference to [this line](https://github.com/localForage/localForage-observable/blob/master/dist/localforage-observable.es6.js#L414) in the localforage-observable library. 

I've tried adding 

```
import {Observable} from 'rxjs/Observable';
```

above the other imports and that doesn't change anything.

**Comment by jloosli** [comment]
Also, I can confirm that I no longer have the `window` error with v1.1.1

**Comment by thgreasi** [comment]
@jloosli Thanks for the instant feeback :+1: 
I'm think I will be able to release v1.2.0 tomorrow.

**Comment by thgreasi** [comment]
I just opened #11 that hopefully resolves this and #9.
Any feedback will be appreciated.

**Comment by Itrulia** [comment]
@jloosli  your problem stems from the fact that the library is using zen-observables by default. You need to override the factory function like this:


```typescript
this.db$ = fromPromise(localForage.ready()).map(x => localForage);
this.db$.take(1).subscribe(db => {
    db.newObservable.factory = (fn) => Observable.create(fn);
});
```


Can also confirm that everything is working now

**Comment by thgreasi** [comment]
Just released v1.2.0.
Readme now also points to an example Ionic 2 project.

**Comment by jloosli** [comment]
@Itrulia thanks for the heads up on RxJs vs Zen-Observables...I hadn't caught that when looking through the docs. 

For what it's worth, 1.2.0 is working for me with the following in the top of the modules I use it in:

```
import * as localForage from 'localforage';
const lfo = require('localforage-observable');
const localforage = lfo.extendPrototype(localForage);
localforage.newObservable.factory = (subscribeFn) => Observable.create(subscribeFn);
```

For some reason, the only combination of imports/requires that worked was the hybrid thing above.

@thgreasi Thanks for the great work!

**Comment by elsigh** [comment]
fwiw I'm getting this same error trying to use localforage-observable and found this issue.

My code is 
```
import localforage from "localforage";
import "localforage-observable";
```

I've tried a few of the other incantations mentioned but no dice.
using 
localforage@1.7.3
localforage-observable@2.0.1
